require File.dirname(__FILE__) + "/captcha/action.rb"
require File.dirname(__FILE__) + "/captcha/image.rb"
require File.dirname(__FILE__) + "/captcha/config.rb"
require File.dirname(__FILE__) + "/captcha/cipher.rb"
require File.dirname(__FILE__) + "/captcha/generator.rb"